-- Tambahkan scope RW pada data operasional dan seluruh ledger keuangan.
ALTER TABLE lingkungan ADD COLUMN IF NOT EXISTS id_rw INTEGER;
ALTER TABLE infrastruktur ADD COLUMN IF NOT EXISTS id_rw INTEGER;
ALTER TABLE aset ADD COLUMN IF NOT EXISTS id_rw INTEGER;
ALTER TABLE keuangan_global ADD COLUMN IF NOT EXISTS id_rw INTEGER;
ALTER TABLE keuangan_sampah ADD COLUMN IF NOT EXISTS id_rw INTEGER;
ALTER TABLE keuangan_keamanan ADD COLUMN IF NOT EXISTS id_rw INTEGER;
ALTER TABLE keuangan_danasosial ADD COLUMN IF NOT EXISTS id_rw INTEGER;
ALTER TABLE keuangan_danakematian ADD COLUMN IF NOT EXISTS id_rw INTEGER;
ALTER TABLE keuangan_kompensasi ADD COLUMN IF NOT EXISTS id_rw INTEGER;

ALTER TABLE lingkungan ALTER COLUMN id_rw TYPE INTEGER USING NULLIF(id_rw::TEXT, '')::INTEGER;
ALTER TABLE infrastruktur ALTER COLUMN id_rw TYPE INTEGER USING NULLIF(id_rw::TEXT, '')::INTEGER;
ALTER TABLE aset ALTER COLUMN id_rw TYPE INTEGER USING NULLIF(id_rw::TEXT, '')::INTEGER;
ALTER TABLE keuangan_global ALTER COLUMN id_rw TYPE INTEGER USING NULLIF(id_rw::TEXT, '')::INTEGER;
ALTER TABLE keuangan_sampah ALTER COLUMN id_rw TYPE INTEGER USING NULLIF(id_rw::TEXT, '')::INTEGER;
ALTER TABLE keuangan_keamanan ALTER COLUMN id_rw TYPE INTEGER USING NULLIF(id_rw::TEXT, '')::INTEGER;
ALTER TABLE keuangan_danasosial ALTER COLUMN id_rw TYPE INTEGER USING NULLIF(id_rw::TEXT, '')::INTEGER;
ALTER TABLE keuangan_danakematian ALTER COLUMN id_rw TYPE INTEGER USING NULLIF(id_rw::TEXT, '')::INTEGER;
ALTER TABLE keuangan_kompensasi ALTER COLUMN id_rw TYPE INTEGER USING NULLIF(id_rw::TEXT, '')::INTEGER;