-- Migrasi SIMDES: nomor RW/RT disimpan sebagai angka.
-- Jalankan sekali pada database Neon yang sudah berisi schema lama.

ALTER TABLE rt DROP CONSTRAINT IF EXISTS rt_id_rw_fkey;

ALTER TABLE rw ALTER COLUMN id_rw TYPE INTEGER USING NULLIF(id_rw, '')::INTEGER;
ALTER TABLE rt ALTER COLUMN id_rt TYPE INTEGER USING NULLIF(id_rt, '')::INTEGER;
ALTER TABLE rt ALTER COLUMN id_rw TYPE INTEGER USING NULLIF(id_rw, '')::INTEGER;
ALTER TABLE users ALTER COLUMN id_rt TYPE INTEGER USING NULLIF(id_rt, '')::INTEGER;
ALTER TABLE users ALTER COLUMN id_rw TYPE INTEGER USING NULLIF(id_rw, '')::INTEGER;
ALTER TABLE sensus ALTER COLUMN id_rt TYPE INTEGER USING NULLIF(id_rt, '')::INTEGER;
ALTER TABLE sensus ALTER COLUMN id_rw TYPE INTEGER USING NULLIF(id_rw, '')::INTEGER;
ALTER TABLE jompo ALTER COLUMN id_rt TYPE INTEGER USING NULLIF(id_rt, '')::INTEGER;
ALTER TABLE anak ALTER COLUMN id_rt TYPE INTEGER USING NULLIF(id_rt, '')::INTEGER;
ALTER TABLE inklusi ALTER COLUMN id_rt TYPE INTEGER USING NULLIF(id_rt, '')::INTEGER;
ALTER TABLE perusahaan ALTER COLUMN id_rt TYPE INTEGER USING NULLIF(id_rt, '')::INTEGER;
ALTER TABLE lingkungan ALTER COLUMN id_rt TYPE INTEGER USING NULLIF(id_rt, '')::INTEGER;
ALTER TABLE infrastruktur ALTER COLUMN id_rt TYPE INTEGER USING NULLIF(id_rt, '')::INTEGER;
ALTER TABLE aset ALTER COLUMN id_rt TYPE INTEGER USING NULLIF(id_rt, '')::INTEGER;
ALTER TABLE keuangan_global ALTER COLUMN id_rt TYPE INTEGER USING NULLIF(NULLIF(id_rt, ''), 'ALL')::INTEGER;
ALTER TABLE keuangan_sampah ALTER COLUMN id_rt TYPE INTEGER USING NULLIF(NULLIF(id_rt, ''), 'ALL')::INTEGER;
ALTER TABLE keuangan_keamanan ALTER COLUMN id_rt TYPE INTEGER USING NULLIF(NULLIF(id_rt, ''), 'ALL')::INTEGER;
ALTER TABLE keuangan_danasosial ALTER COLUMN id_rt TYPE INTEGER USING NULLIF(NULLIF(id_rt, ''), 'ALL')::INTEGER;
ALTER TABLE keuangan_danakematian ALTER COLUMN id_rt TYPE INTEGER USING NULLIF(NULLIF(id_rt, ''), 'ALL')::INTEGER;
ALTER TABLE keuangan_kompensasi ALTER COLUMN id_rt TYPE INTEGER USING NULLIF(NULLIF(id_rt, ''), 'ALL')::INTEGER;

ALTER TABLE rt ADD CONSTRAINT rt_id_rw_fkey FOREIGN KEY (id_rw) REFERENCES rw(id_rw);